services:
  database:
    image: mysql:8.0
    container_name: sump_db_container
    restart: always
    environment:
      - TZ=America/Toronto
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${SUMP_DB_USER}
      - MYSQL_PASSWORD=${SUMP_DB_PASS}
    ports:
      - "${DB_HOST_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - sump_db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - iot-network

  sump-service:
    build: 
      context: .
      args:
        - REACT_APP_SUMP_API_URL=${REACT_APP_SUMP_API_URL}
        - API_PORT=${API_PORT}         
        - COLLECTOR_PORT=${COLLECTOR_PORT}
    environment:
      - TZ=America/Toronto
      - API_PORT=${API_PORT}
      - BIND_HOST=${BIND_HOST}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - DB_USER=${SUMP_DB_USER}
      - DB_PASS=${SUMP_DB_PASS}
      - STATIC_FOLDER=${STATIC_FOLDER}
    restart: always
    ports:
      - "${SUMP_API_PORT}:${API_PORT}"   
      - "${COLLECTOR_HOST_PORT}:${COLLECTOR_PORT}"
    env_file: .env
    depends_on:
      - database
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  sump_db_data:
