services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-db.sh", "npm", "start"]

  permission_fixer:
    image: alpine
    volumes:
      - ../iotSump:/iotSump
    command: >
      sh -c "chmod +x /iotSump/database/schema.sh"
  shared_db_container:
    image: mysql:8.0
    restart: always
    environment:
      - TZ=America/Toronto
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    depends_on:
      permission_fixer:
        condition: service_completed_successfully
    ports:
      - "${DB_HOST_PORT}:${DB_DOCKER_PORT}"
    volumes:
      - sump_db_data:/var/lib/mysql
      - ./database/schema.sh:/docker-entrypoint-initdb.d/01-init-db.sh
    networks:
      - iot-network

  sump-service:
    build: 
      context: .
      args:
        - PUBLIC_URL=/
        - REACT_APP_SUMP_API_URL=${REACT_APP_SUMP_API_URL}
        - API_PORT=${API_PORT}         
        - COLLECTOR_PORT=${COLLECTOR_PORT}
    environment:
      - TZ=America/Toronto
      - API_PORT=${API_PORT}
      - BIND_HOST=${BIND_HOST}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - STATIC_FOLDER=${STATIC_FOLDER}
    restart: always
    ports:
      - "${SUMP_API_PORT}:${API_PORT}"   
      - "${COLLECTOR_HOST_PORT}:${COLLECTOR_PORT}"
    env_file: .env
    depends_on:
      - shared_db_container
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge
    name: iot-network

volumes:
  sump_db_data:
